

trigger:
- main

#strategy:
 # matrix:
  #  linux:
   #   operatingSystem: ubuntu-latest
    #mac:
     # operatingSystem: macos-latest


pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo do the BUild
    

- stage: Deploy
  jobs:
  - deployment:
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deployement stage dev




