# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(PipelineLevelVariable)
  - job: job2
    steps:
    - bash: echo Build 2nd-Job
    - bash: java --version
    - bash: python --version
    - bash: node --version
    - bash: mvn --version
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)


- stage: deploy
  variables:
    environment: Dev
  jobs:
  - job: Job1
    steps:
    - bash: echo deploy FirstJob
  - job: job2
    steps:
    - bash: echo deploy $(environment)

- stage: Prod_deploy
  jobs:
  - job: Job1
    steps:
    - bash: echo Prod-deploy FirstJob
  - job: job2
    steps:
    - bash: echo Prod-Deploy 2nd-Job
      


