# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo Build FirstJob
  - job: job2
    steps:
    - bash: echo Build 2nd-Job
      
- stage: deploy
  jobs:
  - job: Job1
    steps:
    - bash: echo deploy FirstJob
  - job: job2
    steps:
    - bash: echo deploy 2nd-Job

- stage: Prod_deploy
  jobs:
  - job: Job1
    steps:
    - bash: echo Prod-deploy FirstJob
  - job: job2
    steps:
    - bash: echo Prod-Deploy 2nd-Job
      


